spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/kardex-bd?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
